name: Build Android App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Ionic and Capacitor
        run: npm install -g @ionic/cli @capacitor/core @capacitor/cli

      - name: Create Web Project
        run: |
          mkdir www
          cp index.html www/
          npx cap init "RPS GODS" com.rps.gods --web-dir www
          npx cap add android

      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease # APK banayega
          ./gradlew bundleRelease   # AAB banayega

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Game-APK
          path: android/app/build/outputs/apk/release/*.apk

      - name: Upload AAB (Play Store)
        uses: actions/upload-artifact@v4
        with:
          name: Game-AAB
          path: android/app/build/outputs/bundle/release/*.aab
